openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api-token-auth/:
    post:
      operationId: api_token_auth_create
      tags:
      - api-token-auth
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'
        required: true
      security:
      - tokenAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/application:
    get:
      operationId: api_application_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_application_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/application/{id}:
    get:
      operationId: api_application_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_application_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_application_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/applicationstatus/{id}:
    put:
      operationId: api_applicationstatus_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/applicationstatuses:
    put:
      operationId: api_applicationstatuses_update
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/country:
    get:
      operationId: api_country_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_country_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/country/{id}:
    get:
      operationId: api_country_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_country_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_country_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/employee:
    get:
      operationId: api_employee_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_employee_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/employee/{id}:
    get:
      operationId: api_employee_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_employee_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_employee_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/getapplicationexcel/{olymp_id}:
    get:
      operationId: api_getapplicationexcel_retrieve
      parameters:
      - in: path
        name: olymp_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getgenders:
    get:
      operationId: api_getgenders_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getroles:
    get:
      operationId: api_getroles_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/getstudentfromolymp/{olymp_id}:
    get:
      operationId: api_getstudentfromolymp_retrieve
      parameters:
      - in: path
        name: olymp_id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/olympiada:
    get:
      operationId: api_olympiada_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_olympiada_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/olympiada/{id}:
    get:
      operationId: api_olympiada_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_olympiada_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_olympiada_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/participant:
    get:
      operationId: api_participant_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_participant_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/participant/{id}:
    get:
      operationId: api_participant_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_participant_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/result/{id}:
    get:
      operationId: api_result_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_result_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/results:
    get:
      operationId: api_results_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_results_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/school:
    get:
      operationId: api_school_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_school_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/school/{id}:
    get:
      operationId: api_school_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_school_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_school_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/student:
    get:
      operationId: api_student_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/student/{id}:
    get:
      operationId: api_student_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/subdivision:
    get:
      operationId: api_subdivision_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_subdivision_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/subdivision/{id}:
    get:
      operationId: api_subdivision_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: api_subdivision_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/uploadfile:
    put:
      operationId: api_uploadfile_update
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/user:
    get:
      operationId: api_user_retrieve
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: api_user_create
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          description: No response body
  /api/user/{id}:
    get:
      operationId: api_user_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    AuthToken:
      type: object
      properties:
        token:
          type: string
          readOnly: true
      required:
      - token
    AuthTokenRequest:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - password
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
