# Generated by Django 6.0.3 on 2026-04-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование района')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='Название образовательной организации')),
                ('school_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='schools.subdivision', verbose_name='Местоположение')),
            ],
        ),
    ]
