# Generated by Django 6.0.3 on 2026-04-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('olymp', '0014_participant_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_applications', to='applications.application', verbose_name='Заявка'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_subdivision',
        ),
        migrations.AlterField(
            model_name='participant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_students', to='applications.student', verbose_name='Учащийся'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
