# Generated by Django 6.0.3 on 2026-06-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_student_and_more'),
        ('olymp', '0015_alter_participant_application_remove_student_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['application', 'student__name'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='olympiada',
            name='olymp_specialization',
            field=models.IntegerField(choices=[(0, 'Программирование'), (1, 'Робототехника'), (2, 'Информационная безопасность'), (3, 'Искусственный интеллект')], default=0, verbose_name='Специализация олимпиады'),
        ),
        migrations.AddField(
            model_name='olympiada',
            name='olymp_type',
            field=models.IntegerField(choices=[(0, 'Индивидуальная'), (1, 'Командная')], default=0, verbose_name='Тип олимпиады'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='applications.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='applications.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='applications.student', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='result',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='olymp.participant', verbose_name='Участник'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('application', 'student')},
        ),
    ]
