# Generated by Django 6.0.3 on 2026-04-27 11:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olymp', '0014_participant_result'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, verbose_name='Название страны')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.person')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('course_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Класс обучения')),
                ('special_needs', models.BooleanField(default=False, verbose_name='Ограниченные возможности здоровья')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный номер телефона')),
                ('sex', models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], verbose_name='Пол')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='applications.country', verbose_name='Страна')),
            ],
            bases=('users.person',),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.IntegerField(choices=[(0, 'В ожидании'), (1, 'Принята'), (2, 'Отклонена')], default=0, verbose_name='Статус заявки')),
                ('participate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Класс участия')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.employee', verbose_name='Ответственный')),
                ('olymp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiadas', to='olymp.olympiada', verbose_name='Олимпиада')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.school', verbose_name='Общеобразовательная организация')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_subdivisions', to='schools.subdivision', verbose_name='Местоположение')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='users.employee', verbose_name='Учитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='applications.student', verbose_name='Учащийся')),
            ],
        ),
    ]
