# Generated by Django 6.0.3 on 2026-06-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('olymp', '0015_alter_participant_application_remove_student_country_and_more'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.AddField(
            model_name='application',
            name='participation_type',
            field=models.IntegerField(choices=[(0, 'Индивидуальная'), (1, 'Командная')], default=0, verbose_name='Тип участия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.employee', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='application',
            name='olymp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='olymp.olympiada', verbose_name='Олимпиада'),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='schools.school', verbose_name='Общеобразовательная организация'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='schools.subdivision', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='application',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_applications', to='users.employee', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='applications.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название команды')),
                ('students', models.ManyToManyField(related_name='teams', to='applications.student', verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='applications.application', verbose_name='Заявка')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_student', to='applications.student', verbose_name='Студент (индивидуально)')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_team', to='applications.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('team__isnull', True)), models.Q(('student__isnull', True), ('team__isnull', False)), _connector='OR'), name='applicant_student_or_team_not_both')],
            },
        ),
    ]
